apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: detail
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: detail
      previewService: detail-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: detail
  template:
    metadata:
      labels:
        app: detail
    spec:
      containers:
        - name: detail
          image: 590183956481.dkr.ecr.us-west-2.amazonaws.com/detail:latest
          ports:
            - containerPort: 3000
