apiVersion: v1
kind: Service
metadata:
  name: detail
spec:
  selector:
    app: detail
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: detail-preview
spec:
  selector:
    app: detail
  ports:
    - port: 3000
      targetPort: 3000
