apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 590183956481.dkr.ecr.us-west-2.amazonaws.com/frontend:latest
          ports:
            - containerPort: 9000
