apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: frontend
          image: 590183956481.dkr.ecr.us-west-2.amazonaws.com/frontend:prod
